credentials:
  usernames:
    juan:
      email: prueba
      name: test
      password: '2019'
    ana:
      email: ana@example.com
      name: Ana GÃ³mez
      password: '$2b$12$X0W5.JFge3iG3Q9eFzq3Hu=='

cookie:
  expiry_days: 30
  key: 'some_signature_key'
  name: 'gefeed_cookie'

preauthorized:
  emails: []
