credentials:
  usernames:
    admin:
      email: admin@example.com
      name: admin
      password: $2b$12$Ix/cjxuueLnghgMwpJxXXu.jzOMY5fWicliZnHIvb62s1hXfGyDYO
cookie:
  expiry_days: 30
  key: clave_larga_y_aleatoria_de_32+
  name: gefeed_cookie_dev
preauthorized:
  emails: []
